In [1]:
import numpy as np

### Sparse Matrix

In [2]:
# Creating a matrix using numpy
from scipy import sparse

matrix = np.array([[0, 0, 3],
                   [4, 0, 0],
                   [0, 0, 5]])
matrix.shape

(3, 3)

In [3]:
matrix.size

9

In [4]:
# Create compressed sparse row (CSR) matrix
sparse_matrix = sparse.csr_matrix(matrix)
sparse_matrix

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [5]:
print(sparse_matrix)
# sparse matrix has 3 stored elements out of 9, that only the non-zero elements are stored

  (0, 2)	3
  (1, 0)	4
  (2, 2)	5


### Applying Functions over Each Element

In [6]:
# Use the NumPy vectorized operations to apply functions over each element

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Applying a function to each element
add_100 = lambda i: i + 100

vectorized_add_100 = np.vectorize(add_100)

result = vectorized_add_100(matrix)
result

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [7]:
# You can also use broadcasting for element-wise operations
result_broadcast = matrix + 100
result_broadcast

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [8]:
#is pandas and numpy axis same? Yes
# axis=0 -> column wise operation
# axis=1 -> row wise operation

### Flattening a Matrix

In [9]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

flattened = matrix.flatten()
flattened

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Another way to flatten a matrix is using ravel() which returns a flattened array is faster than flatten() but it returns a view if possible


import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]])

raveled = np.ravel([matrix1, matrix2])
raveled

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [11]:
raveled.shape

(18,)

In [12]:
# Rank of a matrix
np.linalg.matrix_rank(matrix1)
# what is rank of a matrix? The rank of a matrix is the maximum number of linearly independent row or column vectors in the matrix. It indicates the dimension of the vector space spanned by its rows or columns.
# Rank = matrisin bağımsız satır (veya sütun) sayısı.Yani satırlardan kaç tanesi “yeni bilgi” taşıyor, diğerleri bunların toplamı/katı çıkıyorsa onlar bağımlıdır.

2