In [2]:
import numpy as np
from dateutil.rrule import SECONDLY
from scipy.sparse import random_array

In [4]:
my_list = [1, 2, 3]
type(my_list)

list

In [6]:
my_numpy_array = np.array(my_list)

In [8]:
my_numpy_array.shape

(3,)

# Matrices

In [10]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_numpy_matrix = np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print(my_numpy_matrix)
type(my_numpy_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [16]:
print(my_matrix)
type(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

# Dot Product

In [19]:
# Dot product of two arrays
a = np.array([1, 2])
b = np.array([3, 4])
dot_product = np.dot(a, b)
print(dot_product)
print(dot_product.shape)

11
()


In [28]:
# Dot product of two matrices
A = np.array([[1, 2],
              [3, 4],
              [5, 6],])

B = np.array([[5, 6, 8, 11],
              [7, 8, 5, 3],])

print(A.shape)
print(B.shape)

# Note: For dot product, the number of columns in A must equal the number of rows
dot_product_matrices = np.dot(A, B)
print(dot_product_matrices)
print(dot_product_matrices.shape)

(3, 2)
(2, 4)
[[19 22 18 17]
 [43 50 44 45]
 [67 78 70 73]]
(3, 4)


In [33]:
first_matrix = np.array([[1, 0, 1],
                         [0, 0, 1]])

second_matrix = np.array([[1, 1, 1, 1],
                          [0, 0, 0, 0],
                          [1, 0, 1, 0]])

print(first_matrix.shape)
print(second_matrix.shape)


(2, 3)
(3, 4)


In [34]:
new_dot_product = np.dot(first_matrix, second_matrix)
print(new_dot_product)
print(new_dot_product.shape)

[[2 1 2 1]
 [1 0 1 0]]
(2, 4)


In [36]:
new_array = np.random.randint(1,100,20) # 20 random integers between 1 and 100
print(new_array)

[60 61 17 86 56 77 30 12 71 21 18 60  3 27 93 77 74 68 22 99]


In [37]:
new_array > 25

array([ True,  True, False,  True,  True,  True,  True, False,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
       False,  True])

In [38]:
new_array[new_array > 25]

array([60, 61, 86, 56, 77, 30, 71, 60, 27, 93, 77, 74, 68, 99])

# Transpose and Reshape


In [41]:
second_matrix.shape

(3, 4)

In [43]:
transpose_second_matrix = second_matrix.T # or np.transpose(second_matrix)
print(transpose_second_matrix.shape)
print(transpose_second_matrix)

(4, 3)
[[1 0 1]
 [1 0 0]
 [1 0 1]
 [1 0 0]]


In [48]:
random_array = np.random.random((3,2))
random_array

array([[0.70737742, 0.15972955],
       [0.76198492, 0.13391744],
       [0.69285824, 0.91953213]])

In [49]:
random_array.shape

(3, 2)

In [52]:
random_array.reshape(6,1) # or random_array.reshape(2,3) 2x3 = 6x1

array([[0.70737742],
       [0.15972955],
       [0.76198492],
       [0.13391744],
       [0.69285824],
       [0.91953213]])

In [53]:
data = np.array([10, 12, 15, 18, 20, 25, 100, 150])

In [55]:
mean = np.mean(data)
print(mean)

43.75


In [57]:
std = np.std(data)
print(std)

48.74102481483129


In [58]:
z_scores = (data - mean) / std
print(z_scores)

[-0.69243517 -0.65140198 -0.58985219 -0.52830239 -0.4872692  -0.38468621
  1.15405862  2.17988851]


In [60]:
data[z_scores > 1] # Values with z-score greater than 1 for outlier detection

array([100, 150])

In [61]:
#math equation
# 2x + 3y = 8 and 5x + 7y = 19

A = np.array([[2, 3], [5, 7]]) # Coefficient matrix 2x,3y and 5x,7y
B = np.array([8, 19])          # Ordinate matrix 8 and 19

solution = np.linalg.solve(A, B)
print(solution) # x and y values

[1. 2.]
